#!/usr/bin/env python

import sys, os

import matplotlib.pyplot as plt
from gprot.plots import trace_plot

import argparse

parser = argparse.ArgumentParser()

parser.add_argument('star', type=int)
parser.add_argument('--directory', '-d', default='mcmc_chains')

args = parser.parse_args()

fig = trace_plot(args.star, directory=args.directory)

plt.show()
