#!/usr/bin/env python

import sys, os
import logging

import numpy as np

from gprot.aigrain import AigrainLightCurve
from gprot.kepler import KeplerLightCurve

def get_prot(i, aigrain=True, kepler=False, pmax=[10,30,100]):
    try:
        if aigrain:
            lc = AigrainLightCurve(i)
        elif kepler:
            lc = KeplerLightCurve(i)

        return [lc.acf_prot(pmax=p) for p in pmax]
    except:
        return [[np.nan]*4 for p in pmax]

class ProtWorker(object):
    """
    """
    def __init__(self, verbose=False, **kwargs):
        self.kwargs = kwargs
        self.verbose = verbose

    def __call__(self, i):
        if self.verbose:
            print(i)
        return get_prot(i, **self.kwargs)

if __name__=='__main__':
    import argparse
    import schwimmbad

    parser = argparse.ArgumentParser(description='Calculate ACF prots for given stars')

    parser.add_argument('stars', nargs='*', type=int, help='Stars to fit.')
    parser.add_argument('--file', '-f', default=None, help='filename of list of stars.')
    parser.add_argument('--pmax', nargs='+', type=int, default=[1,2,4,8,16,32,64,128])
    parser.add_argument('--verbose', '-v', action='store_true')

    datagroup = parser.add_mutually_exclusive_group()
    datagroup.add_argument("--aigrain", dest="aigrain", action='store_true',
                        default=True,
                       help="Use Aigrain simulations.")
    datagroup.add_argument("--kepler", dest="kepler", action='store_true',
                       help="Use Kepler data.")

    group = parser.add_mutually_exclusive_group()
    group.add_argument("--ncores", dest="n_cores", default=1,
                       type=int, help="Number of processes (uses multiprocessing).")
    group.add_argument("--mpi", dest="mpi", default=False,
                       action="store_true", help="Run with MPI.")

    args = parser.parse_args()
    if args.kepler:
        args.aigrain = False

    pool = schwimmbad.choose_pool(mpi=args.mpi, processes=args.n_cores)

    worker = ProtWorker(pmax=args.pmax, aigrain=args.aigrain, kepler=args.kepler,
                        verbose=args.verbose)
    
    if args.file is not None:
        stars = np.loadtxt(args.file, dtype=int)
    else:
        stars = args.stars

    prots = pool.map(worker, stars)

    sys.stdout.write('star ')
    sys.stdout.write('pmax prot height tau quality\n')
    # for p in args.pmax:
    #     sys.stdout.write('prot_{0} height_{0} tau_{0} quality_{0} '.format(p))
    # sys.stdout.write('\n')
    for star, results in zip(stars, prots):

        # sys.stdout.write('{} '.format(star))
        for i,(p, h, tau, q) in enumerate(results):
            sys.stdout.write('{} {:.0f} {:.3f} {:.3f} {:.3f} {:.2f}\n'.format(star, args.pmax[i], 
                                                                    p, h, tau, q))
        # sys.stdout.write('\n')
